service: slackbot-anniversary-reminder
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 30
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    ANNIVERSARY_MESSAGE_CHANNEL: ${env:ANNIVERSARY_MESSAGE_CHANNEL}
    ANNIVERSARY_MESSAGE_HOURS: ${env:ANNIVERSARY_MESSAGE_HOURS}
    ANNIVERSARY_MESSAGE_MINUTES: ${env:ANNIVERSARY_MESSAGE_MINUTES}
    ANNIVERSARY_MESSAGE_DELAY_IN_SECONDS: ${env:ANNIVERSARY_MESSAGE_DELAY_IN_SECONDS}
    ANNIVERSARY_SPREADSHEET_ID: ${env:ANNIVERSARY_SPREADSHEET_ID}
    GOOGLE_SERVICE_ACCOUNT_EMAIL: ${env:GOOGLE_SERVICE_ACCOUNT_EMAIL}
    GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}

plugins:
  - serverless-offline
  - serverless-offline-scheduler

functions:
  send-anniversary-message:
    handler: src/functions/cron/send-anniversary-message.func
    events:
      # run every day at 9:00AM UTC+0
      - schedule: cron(0 9 * * ? *)
